site_name: Wing's Notebook
site_url: https://wing0night.github.io/Wing-s_Notebook/
site_description: Wing's Notebook
repo_name: wing0night/Wing-s_Notebook
repo_url: https://github.com/wing0night/Wing-s_Notebook
edit_uri: tree/master/docs

copyright: Copyright &copy; 2024 Wing0Night

nav:
  - About me and this website:
    - AboutMe/index.md
    - It's a template: AboutMe/template.md
  - 有意思的探索:
    - 计网抓包小实验: InterestingExploration/计网抓包小实验.md
  - Lessons in ZJU:
    - 有意思的通识课:
      - 视唱练耳: LessonsInZJU/InterestingClasses/视唱练耳.md
    - 主修_Chem:
      - 量子化学: LessonsInZJU/MajorCourses_Chem/量子化学.md
      - 普通化学: LessonsInZJU/MajorCourses_Chem/普通化学.md
    - 主修_Control:
      - 计算机网络原理: LessonsInZJU/MajorCourses_Control/计网.md
      - 嵌入式系统: LessonsInZJU/MajorCourses_Control/嵌入式系统.md
    - 数理基础:
      - 概率论和数理统计: LessonsInZJU/MathematicBasic/概率论和数理统计.md
      - 普通物理学(H): LessonsInZJU/MathematicBasic/普通物理学H.md
      - 微积分: LessonsInZJU/MathematicBasic/微积分.md


theme:
  features:
    #- toc.integrate #合并左右边栏
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.footer
    - content.action.edit
    - content.code.annotate
  language: zh
  name: material
  custom_dir: overrides
  logo: 'icons/Services.png'
  palette:
    #scheme: myscheme
    # Toggle light mode
    - media: "(prefers-color-scheme: dark)"
      scheme: mydark
      #primary: yellow
      #accent: yellow
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

    # Toggle dark mode
    - media: "(prefers-color-scheme: light)"
      scheme: mylight
      #primary: yellow
      #accent: yellow
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

  

  font:
    text: Roboto

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.details # 需要点击才能展开的高亮块
  - pymdownx.blocks.admonition: # 必然展开的高亮块
      types:
      - new # type 能填哪些项，从这里就能找到
      - settings
      - note
      - abstract
      - info
      - tip
      - success
      - question
      - warning
      - failure
      - danger
      - bug
      - example
      - quote
  - pymdownx.blocks.tab:
      alternate_style: True

extra_css:
  - CSS/extra.css
  - CSS/card.css
  - CSS/label.css
  - CSS/custom.css
  - https://cdn.jsdelivr.net/npm/lxgw-wenkai-webfont@1.1.0/style.css
  # - https://cdn.jsdelivr.net/npm/lxgw-wenkai-lite-webfont@1.1.0/style.css
  # - https://cdn.jsdelivr.net/npm/lxgw-wenkai-tc-webfont@1.0.0/style.css
  # - https://cdn.jsdelivr.net/npm/lxgw-wenkai-screen-webfont@1.1.0/style.css





